--------------------------------------------------------
--  File creato - domenica-novembre-24-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "C##NERVHIBERNATE"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."USERS" 
   (	"USERID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 CHAR), 
	"SURNAME" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERMEMBERS_STATS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" 
   (	"IDMEMBERSTATS" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"LEVELPG" NUMBER(10,0), 
	"EXP" NUMBER(10,0), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"STATUS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIMULATIONS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."SIMULATIONS" 
   (	"SIMULATIONID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 CHAR), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"EXP" NUMBER(10,0), 
	"LEVELMIN" NUMBER(10,0), 
	"DURATIONTIME" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" 
   (	"SIMULATIONPARTICIPANTID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SIMULATIONID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" 
   (	"MISSIONPARTICIPANTSID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MISSIONID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MISSION_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" 
   (	"MISSIONARCHIVEID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MISSIONID" NUMBER(10,0), 
	"MISSION_CODE" VARCHAR2(255 CHAR), 
	"USERID" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"STARTTIME" TIMESTAMP (6), 
	"ENDTIME" TIMESTAMP (6), 
	"TACTICALABILITY" NUMBER(10,0), 
	"SYNCHRATE" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"RESULT" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION" 
   (	"MISSIONID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"IMAGEMISSION" BLOB, 
	"PARTICIPANTSMAX" NUMBER(10,0), 
	"LEVELMIN" NUMBER(10,0), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"EXP" NUMBER(10,0), 
	"DURATIONTIME" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGEMISSION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MEMBERS" 
   (	"MEMBERID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 CHAR), 
	"SURNAME" VARCHAR2(255 CHAR), 
	"ALIAS" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NERVHIBERNATE.USERS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.USERMEMBERS_STATS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.SIMULATIONS
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.SIMULATIONS (SIMULATIONID,NAME,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,LEVELMIN,DURATIONTIME) values ('22','RESCUE MISSION','10','-20','10','100','0','1');
Insert into C##NERVHIBERNATE.SIMULATIONS (SIMULATIONID,NAME,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,LEVELMIN,DURATIONTIME) values ('23','INFILTRATION MISSION','-20','10','10','100','0','1');
Insert into C##NERVHIBERNATE.SIMULATIONS (SIMULATIONID,NAME,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,LEVELMIN,DURATIONTIME) values ('21','ANGEL FIGHT','10','10','-20','100','0','1');
REM INSERTING into C##NERVHIBERNATE.SIMULATION_PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.MISSION_PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.MISSION_ARCHIVE
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.MISSION
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('24','Showdown in Tokyo-3','Ramiel, a geometric angel, hovers over Neo Tokyo-3. Its devastating energy beam repels all attacks. Only a long-range strategy can stop it.','2','15','60','45','40','300','7');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('25','Asuka Strikes!','An angel attacks a military fleet from the sea. Fighting Gaghiel underwater tests Evangelion''s ability to adapt to harsh marine conditions.','2','20','70','55','60','300','8');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('22','Angel Attack','A giant angel, Sachiel, emerges from the sea, heading toward Neo Tokyo-3. Conventional defenses are useless. NERV deploys Evangelion, but the angel shows incredible resistance and regeneration.','1','2','40','35','25','100','5');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('23','A Transfer','Shamshel, an angel with energy whips, attacks the city. Its agility and lethality force Evangelion into close combat to stop it.','1','5','50','30','35','200','6');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('26','Both of You, Dance Like You Want to Win!','Israfel splits into two synchronized entities. The mission requires perfect cooperation to strike both targets at the same time.','2','25','75','65','65','350','9');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('27','Magma Diver','A dormant angel awakens inside a volcano. The mission to capture Sandalphon turns into a desperate fight in a volatile environment.','1','30','60','70','55','350','10');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('28','The Day Tokyo-3 Stood Still','During a blackout, Matarael attacks Neo Tokyo-3 with acid. With no technology available, improvised solutions are the only hope.','2','35','50','60','45','400','10');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('29','She Said, Don''t Make Others Suffer','Sahaquiel, a giant angel, tries to crash into Neo Tokyo-3. Interception is critical, but its size and ranged attacks make it a challenge.','2','40','65','80','75','900','11');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('30','Lilliputian Hitcher','A microscopic angel invades NERV, infecting its systems. The mission demands intelligence to outsmart the rapidly evolving enemy.','1','50','55','60','80','950','12');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('31','Oral Stage','A parasitic angel infects an Evangelion, using it to attack. The mission is to stop Bardiel without destroying the infected unit.','3','60','70','50','60','500','13');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('32','Splitting of the Breast','Leliel appears as a giant black sphere. Its two-dimensional shadow warps reality, making entry into its dimension the only option.','2','65','80','70','65','450','14');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('33','Ambivalence','Zeruel, an angel of massive power, attacks NERV, breaking defenses with energy blasts and blades. Only a direct confrontation can stop it.','3','70','85','90','85','950','15');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('34','Introjection','Zeruel''s attack on NERV intensifies. The pilots must risk everything in a desperate battle to stop its devastating advance.','3','80','90','80','90','1000','16');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('35','He Was Aware That He Was Still a Child','Arael attacks with a psychic assault from orbit. The mission challenges both the pilots'' physical and emotional resilience.','2','85','65','55','70','1500','17');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('36','Don''t Be','Armisael, a fluid angel, threatens to merge with the Evangelion units. The mission is to stop it before its dangerous connection is complete.','2','90','90','75','80','2000','18');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('37','Kaworu Nagisa','Tabris infiltrates NERV, blurring the line between ally and enemy. The mission is to prevent him from reaching Terminal Dogma.','3','100','100','90','85','3000','20');
Insert into C##NERVHIBERNATE.MISSION (MISSIONID,NAME,DESCRIPTION,PARTICIPANTSMAX,LEVELMIN,SYNCHRONIZATIONRATE,TACTICALABILITY,SUPPORTABILITY,EXP,DURATIONTIME) values ('38','Take Care of Yourself','The final mission is a personal battle against inner demons. The pilots must confront their fears in a race against time.','3','100','100','100','100','5000','25');
REM INSERTING into C##NERVHIBERNATE.MEMBERS
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.MEMBERS (MEMBERID,NAME,SURNAME,ALIAS) values ('27','Shinji','Ikari','Third Children');
Insert into C##NERVHIBERNATE.MEMBERS (MEMBERID,NAME,SURNAME,ALIAS) values ('25','Rei','Ayanami','First Children');
Insert into C##NERVHIBERNATE.MEMBERS (MEMBERID,NAME,SURNAME,ALIAS) values ('26','Asuka','Soryu Langley','Second Children');
--------------------------------------------------------
--  DDL for Index SYS_C009207
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009207" ON "C##NERVHIBERNATE"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009201
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009201" ON "C##NERVHIBERNATE"."USERMEMBERS_STATS" ("IDMEMBERSTATS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009199
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009199" ON "C##NERVHIBERNATE"."SIMULATIONS" ("SIMULATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009197
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009197" ON "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ("SIMULATIONPARTICIPANTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009192
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009192" ON "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ("MISSIONPARTICIPANTSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009187
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009187" ON "C##NERVHIBERNATE"."MISSION_ARCHIVE" ("MISSIONARCHIVEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009176
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009176" ON "C##NERVHIBERNATE"."MISSION" ("MISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009165
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009165" ON "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERMEMBERS_STATS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" MODIFY ("IDMEMBERSTATS" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD PRIMARY KEY ("IDMEMBERSTATS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATIONS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATIONS" MODIFY ("SIMULATIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATIONS" ADD PRIMARY KEY ("SIMULATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" MODIFY ("SIMULATIONPARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" MODIFY ("SIMULATIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD PRIMARY KEY ("SIMULATIONPARTICIPANTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" MODIFY ("MISSIONPARTICIPANTSID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" MODIFY ("MISSIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD PRIMARY KEY ("MISSIONPARTICIPANTSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("MISSIONARCHIVEID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("MISSIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("MISSION_CODE" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("TACTICALABILITY" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("SYNCHRATE" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("SUPPORTABILITY" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD PRIMARY KEY ("MISSIONARCHIVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("MISSIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("PARTICIPANTSMAX" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("LEVELMIN" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("SYNCHRONIZATIONRATE" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("TACTICALABILITY" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("SUPPORTABILITY" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("EXP" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("DURATIONTIME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" ADD PRIMARY KEY ("MISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MEMBERS" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MEMBERS" ADD PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERMEMBERS_STATS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD CONSTRAINT "FKOEGOT7Q2T64YL6TSBRKWUF8JC" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD CONSTRAINT "FKALKNQXI3KR8F2VW9QEQJTCF19" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKOYHWASJ9J7MF7S9RFG51JYMA5" FOREIGN KEY ("SIMULATIONID")
	  REFERENCES "C##NERVHIBERNATE"."SIMULATIONS" ("SIMULATIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKLN6RK7BAI54TEY9904OBXM23E" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKE3YGWK0O89JLCOC0R088WHOLE" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FKD7W31KFBB4P8YQXV6GHAIYAVK" FOREIGN KEY ("MISSIONID")
	  REFERENCES "C##NERVHIBERNATE"."MISSION" ("MISSIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FK16BIPHO844NE3HVF69WWXVUYJ" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FKSUXD7XLHQ3B7GDTEX189M29OE" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSION_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FKIDWOCO4PFBPLNHNKK0LIELSNU" FOREIGN KEY ("MISSIONID")
	  REFERENCES "C##NERVHIBERNATE"."MISSION" ("MISSIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FK60F30SM29C2V3TBCBFK1A526B" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FKP49EJK645VX5J6MIU0S42BMGA" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
